name: auth_test
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.0.5 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  mobile_scanner: ^3.3.0
  google_maps_flutter: ^2.3.1
  google_maps_flutter_web: ^0.5.1
  qr_flutter: ^4.1.0
  firebase_auth: ^4.6.3
  firebase_core: ^2.14.0
  flutter_svg: ^2.0.7
  cloud_firestore: ^4.8.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
